name: build

on:
  workflow_dispatch:
  push:
    paths:
      - '*'  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main       
 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          wrhsd/binggogo:latest
          wrhsd/binggogo:${{ steps.date.outputs.today }}
